data_free: true
enable_gradnorm: false
opt_epochs: 20000
training:
  seed: 42
  epochs: 20000
  learning_rate: 0.0032659720145241655
  batch_size: 1024
scenario: one_building_DEM_zero
model:
  name: DGMNetwork
  output_dim: 3
  width: 256
  depth: 4
domain:
  lx: 1200.0
  ly: 100.0
  t_final: 3600.0
sampling:
  n_points_pde: 100000
  n_points_ic: 2000
  n_points_bc_domain: 20000
  n_points_bc_building: 8000
building:
  x_min: 325.0
  x_max: 375.0
  y_min: 25.0
  y_max: 75.0
  nx: 16
  ny: 6
  nt: 9
physics:
  u_const: 0.29
  n_manning: 0.03
  inflow: null
  g: 9.81
loss_weights:
  pde_weight: 1.0
  ic_weight: 295.4074961508369
  bc_weight: 44.544026237093846
  building_bc_weight: 1.1104102708123706
  data_weight: 0.0
  h_neg_weight: 10.0
gradnorm:
  learning_rate: 0.01
  enable: false
plotting:
  nx_val: 101
  t_const_val: 1800.0
  y_const_plot: 0
  plot_resolution: 150
device:
  dtype: "float32"
  early_stop_min_epochs: 40000
  early_stop_patience: 30000
numerics:
  eps: 1.0e-06
CONFIG_PATH: optimisation/configs/hpo_DGM_datafree_static.yaml
