hpo_settings: {data_free: true, enable_gradnorm: false, opt_epochs: 2000}
scenario: "one_building_DEM_zero"
domain: {lx: 1200.0, ly: 100.0, t_final: 3600.0}
physics: {g: 9.81, inflow: null, n_manning: 0.03, u_const: 0.29}
device: {dtype: float32, early_stop_min_epochs: 4000, early_stop_patience: 3000}
numerics: {eps: 1.0e-06}
plotting: {nx_val: 101, plot_resolution: 150, t_const_val: 1800.0, y_const_plot: 0}
training: {epochs: 2000, seed: 42}
building: {x_max: 375.0, x_min: 325.0, y_max: 75.0, y_min: 25.0}
model: {name: MLP, output_dim: 3}

hpo_hyperparameters:
  learning_rate: {min: 1.0e-06, max: 0.01, log: true}
  batch_size: [256, 512, 1024]
  model_width: [128, 256, 512, 1024]
  model_depth: {min: 3, max: 6}
  sampling:
    n_points_pde: {min: 10000, max: 120000, log: true}
    n_points_ic: {min: 1000, max: 20000, log: true}
    n_points_bc_domain: {min: 4000, max: 40000, log: true}
    n_points_bc_building: {min: 1000, max: 20000, log: true}
  loss_weights:
    pde_weight: {min: 1.0, max: 1.0e+06, log: true}
    ic_weight: 1.0
    bc_weight: {min: 0.01, max: 1000.0, log: true}
    neg_h_weight: {min: 0.01, max: 1000.0, log: true}
    building_bc_weight: 1.0